version: "3"

services:
  crm-nginx-testing:
    image: nginx:1.17
    ports:
      - "8210:80"
    volumes:
      - ./:/var/www
      - ./deploy/nginx/testing.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - crm-php-fpm-testing
    networks:
      - crm-network-testing

  crm-php-fpm-testing:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    volumes:
      - ./app:/var/www/app
      - ./bootstrap:/var/www/bootstrap
      - ./config:/var/www/config
      - ./database:/var/www/database
      - ./public:/var/www/public
      - ./resources:/var/www/resources
      - ./routes:/var/www/routes
      - ./storage:/var/www/storage
      - ./tests:/var/www/tests
      - ./.env:/var/www/.env
      - ./artisan:/var/www/artisan
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./phpunit.xml:/var/www/phpunit.xml
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - crm-mysql-testing
    networks:
      - crm-network-testing

  crm-mysql-testing:
    image: mysql:8
    volumes:
      - ./docker/mysql-testing:/var/lib/mysql
    ports:
      - "33081:3306"
    environment:
      MYSQL_DATABASE: crm_test
      MYSQL_USER: crm_test
      MYSQL_PASSWORD: crm_test
      MYSQL_ROOT_PASSWORD: super_srm_test
    networks:
      - crm-network-testing

  crm-redis-testing:
    image: redis:4

networks:
  crm-network-testing:
    driver: bridge
